language: python

cache: apt

python:
  - "2.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.settings 
    - COLAB_SETTINGS=tests/settings.yaml

install:
  - pip install coveralls flake8
  - pip install .
  - psql -c "CREATE USER colab WITH PASSWORD 'colab' CREATEDB;" -U postgres

before_script: 
  - colab-admin build_solr_schema > /tmp/schema.xml
  - cat ci/install_solr.sh | SOLR_VERSION=4.10.3  SOLR_CONFS="/tmp/schema.xml" bash

script:
  - python setup.py test
  - flake8 colab

after_success:
  - coveralls
  - ci/build_rpm.sh
