language: python

sudo: false

python:
  - "2.7"

env:
  global:
    - COLAB_SETTINGS=tests/colab_settings.py

install:
  - pip install coveralls flake8 behave behave_django
  - pip install .

script:
  - python setup.py test
  - colab-admin behave
  - flake8 colab

after_success:
  - coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net#colab"
    on_success: change
    on_failure: always
    use_notice: true
