language: python

sudo: false

python:
  - "2.7"

env:
  global:
    - DJANGO_SETTINGS_MODULE=tests.settings

install:
  - pip install coveralls flake8
  - pip install .

script:
  - python setup.py test
  - flake8 colab

after_success:
  - coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net#colab"
    on_success: change
    on_failure: always
    use_notice: true
