language: python

cache: apt

python:
  - "2.7"

env:
  - DJANGO_SETTINGS_MODULE=tests.settings COLAB_SETTINGS=tests/settings.yaml

install:
  - pip install coveralls flake8
  - pip install .
  - psql -c "CREATE USER colab WITH PASSWORD 'colab' CREATEDB;" -U postgres

before_script: 
  - colab-init-config > /etc/colab/settings.yaml
  - colab-admin build_solr_schema > solr_confs/schema.xml
  - SOLR_VERSION=4.10.3 SOLR_CONFS="solr_confs" exec  `pwd`/ci/install_solr.sh
  - colab-admin rebuild_index

script:
  - python setup.py test
  - flake8 colab

after_success:
  - coveralls
  - ci/build_rpm.sh
