language: python

cache: apt

python:
  - "2.7"

install:
  - pip install coveralls flake8
  - pip install .
  - psql -c "CREATE USER colab WITH PASSWORD 'colab' CREATEDB;" -U postgres

script:
  - python setup.py test
  - flake8 colab

before_script: 
  - colab-admin build_solr_schema > schema.xml 
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.10.2 bash 

after_success:
  - coveralls
  - ci/build_rpm.sh
